### ISSUE TITLE
dbux-projects: Easily work through "sample bugs" + keep record of progress locally

### ISSUE THREAD

**Issue by Domiii** [Domiii/dbux#118]
* [x] When clicking on a bug, open a TextEditor, showing a bug's introduction
   * [x] Ideally, we want to use the builtin Markdown preview window, but that does not seem possible. Probably need to use Webview to render instead. Consider VSCode Webview sample for this.
      * [x] Need to prepare an `html` template for this.
* [x] Allow user to store their bug solutions locally:
   * [x] Use [VSCode's Memento API](https://stackoverflow.com/questions/51821924/how-to-persist-information-for-a-vscode-extension) to store things locally
   * [x] DataStructure: `TestRun`
      1. `projectId` + `bugId`
      1. `createdAt`
      1. `nFailedTests` number of tests failed (statusCode)
      1. `timer` time spent (or null, if no timer was used)
      1. `patch` string containing complete patch contents, obtained via `Project.getPatchString`
   * [x] DataStructure: `BugProgress`
      1. `projectId` + `bugId` (combined PrimaryKey)
      1. `createdAt` + `updatedAt`
      1. `stopwatchEnabled` + `timePassed`
      1. `status` (`BugStatus = new Enum({ None: 1, Solving: 2, Attempted: 3, Solved: 4 })`)
   * NOTE: we will add `id` and `uid` columns to these data-structures when moving it online
* [x] Complete "PracticeSession" concept
   * [x] When "activating" a bug for the first time, allow user to choose whether they want to time their results (see `codeModals.js` -> `showInformationMessage`)
      * [x] If they choose to time it, start timer (implemented in `PracticeStopwatch.js`)
   * [x] While timer is running, and user clicks the timer, selects another bug or cancels current bug run, confirm with user to stop timer. If confirmed, stop timer and store partial results (see below) before "cancelling" current bug.
   * [x] when a bug testCommand has finished running:
      * [x] Store a `TestRun` object in `ProgressLog`
      * [x] the result `statusCode` obtained from the terminal is actually the number of failed tests. Show that result to the user. If `testCommand` executed and no test failed:
         * [x] include a message of success and encouragement  🎉🎉🎉  
         * [x] `updateOrCreate` corresponding `BugStatus` with `status = BugStatus.Solved`
         * [x] "clear bug" from `BugRunner` so it is no longer active. Maybe we can just call cancel?
   * [x] associate each session with a `sessionId`
   * [ ] store sessions, testRuns + bugStatus in db
* [x] In `ProjectView`, show bugs where `status == BugStatus.Solved` with a checkmark icon
* [x] When `ProjectView` is visible for the first time, load `ProgressLog` from `Memento` and render previous progress in UI
* [x] Allow user to switch between bugs without any problems
   * [x] Always prompt user for confirmation before running `gitResetHard` when `git diff` result is not empty.
   * [x] When activating a bug and user has an active bug (`BugRunner.getActiveBug`), store `TestRun` with `nFailedTests = -1` (marking an attempt, but without test run)
      * [x] If previous bug is unknown (e.g. because we restarted VScode):
         1. get tag name (`Project.getTagName`)
         1. get `bugId` from looking it up in the `getOrLoadBugs` array by tag name
         1. store `TestRun` (with patch!)
         1. then `gitResetHard`
   * [x] When activating a bug that already has any `TestRun`s, choose the latest `TestRun` and apply that patch
      * [x] Finish `Project.applyPatchString` in order to apply a patch from string (rather than file)
   * [x] Allow user to review their changes using the VSCode built-in diff viewer (can we use [`code -d <file1> <file2>`](https://code.visualstudio.com/docs/editor/command-line)? -> might not be sufficient since there are multiple files and it cannot diff entire directories this way?)

* [x] Make sure, dbux-practice view is refreshed even if `activateBug` failed

**Comment by MiccWan** [comment]
![IMG_20200723_170528](https://user-images.githubusercontent.com/16610454/88269595-e729de00-cd06-11ea-85e9-c96b8f294d16.jpg)
