### ISSUE TITLE
[dataProviderUtil] can't find callerTraceOfContext by parentTrace

### ISSUE THREAD

**Issue by Domiii** [Domiii/dbux#122]
Sometimes caller trace cannot be found.

Are `callId` or `resultCallerId` not set?
How to reproduce?

https://github.com/Domiii/dbux/blob/dev/dbux-data/src/dataProviderUtil.js#L393

**Comment by MiccWan** [comment]
Reproduce with project:  Express Bug#1

**Comment by Domiii** [comment]
fixed
