### ISSUE TITLE
Call Graph Grouping: insert new virtual `GroupNode`s into Call Graph

### ISSUE THREAD

**Issue by Domiii** [Domiii/dbux#124]
* [ ] `ContextGroupNode`: multiple `context`s (`realContext`) of same `parentTraceId`
* [ ] `RecursionGroupNode`: multiple `staticContext` of same `staticContextId` repeated in a single run
   * (e.g. `next` in `express`)
* (Future work: `LoopNode` for loops)

**Comment by MiccWan** [comment]
need to add `group` concept to dbux-data

**Comment by MiccWan** [comment]
@Domiii Is #464 duplicate with this?

**Comment by Domiii** [comment]
@MiccWan  Not quite, since this issue is more general. However, due to lack of developer resources, will close this for now anyway.
