### ISSUE TITLE
Add "Toggle RuntimeServer" button to "Applications" TreeView

### ISSUE THREAD

**Issue by Domiii** [Domiii/dbux#161]
The button should render the current RuntimeServer state (e.g. a "router" icon in green/red).
When clicked start/stop the server.

Also see: #135

**Comment by MiccWan** [comment]
Currently `SocketServer.js` provides `initRuntimeServer()` and `stopRuntimeServer()` to toggle RuntimeServer, but it used `makeListenSocket`@serverUtil.js to create `httpServer`, which will create a singleton httpServer and wont dispose at `stopRuntimeServer`, the port is still occupied. Not sure if this is intended.

@Domiii 
I've done the changes to this issue, maybe create PR after u review this.

**Comment by MiccWan** [comment]
Transfer to @edisonhello
