### ISSUE TITLE
child_process functions very slow in VSCode (Electron)

### ISSUE THREAD

**Issue by Domiii** [Domiii/dbux#193]
Has been brought up [here](https://stackoverflow.com/questions/57967438/child-process-methods-are-slow-on-electron).

We want to move all long-running processes (`git clone`, `npm install` etc) to `TerminalWrapper`.

**Comment by edisonhello** [comment]
- [ ] Need to replace `\` with `/` in path.

**Comment by Domiii** [comment]
#213 is looking good, but needs small amendment:

* [ ] Need a `watcher.on('error')` to handle errors gracefully

**Comment by MiccWan** [comment]
I have tested and found some problem, @edisonhello tell me when u have resolve them
