### ISSUE TITLE
show neighboring trace values in traceDetailsView

### ISSUE THREAD

**Issue by Domiii** [Domiii/dbux#195]
One great value of the traditional debugger is to see the value of variables in context in one table. Useful feature to have.

Dbux currently does not quite comprehend "variables", as we deal in traces and have not analyzed the role of individual variables yet - but at least we can show expression values of nearby expressions?

For now, we can:

1. Add new "Nearby Traces" node to traceDetailsView
1. One node per contexts on the current callstack just like the traditional debugger does it with scopes.
1. One node per staticTrace (that are expressions) of that context
1. Value of the actual trace that got executed in that context, closest to `selectedTrace`
1. Visualize with `node's label` = `staticTrace label` and `node's description` = `traceValueLabel`

The screenshot shows how VSCode is now grouping by block, but I think that just makes things more confusing.

We can just group by context, makes things more intuitive to my mind. (I think that is how they used to do it, too.)

![image](https://user-images.githubusercontent.com/282899/89891546-d97dbf00-dc07-11ea-9d28-da77cec5295a.png)

Thoughts?

**Comment by MiccWan** [comment]
Maybe we need `variable` concept to keep trace the `newest value` of the variable in the current frame?
Only try to list all value trace(exclude undefined) in current context now.
