### ISSUE TITLE
traces inside of a try block are not flagged as error, even if error was thrown

### ISSUE THREAD

**Issue by Domiii** [Domiii/dbux#197]
## Problem

* Error thrown in `try` block does not get detected correctly.
* If error was thrown, first trace of `finally` block will be flagged as `error` trace (incorrectly).

## Examples

* `error4.js`: error trace flagged incorrectly - should be `todos` (before `todos.x`) but is on `=` trace instead.
  * similar issue in `error2.js` - <img src="https://user-images.githubusercontent.com/282899/141737260-8c98a23d-542d-451b-b815-5e068cba90fa.png" width="200"> 
  * using `previousTraceInContext` of `PopImmediate` does not work with try-catch cases

## Solution

We are currently only resolving errors from `PopImmediate` in `DataProvider.resolveErrorTraces`. Currently, only traces that are `PopImmediate` and also `!isTraceFunctionExit` are error traces.

* [x] add and instrument new `TraceTypes`:
  * [x] `TraceType.TryBlockExit`
  * [x] `TraceType.Catch`
  * [x] `TraceType.Finally`
* [x] fix up `DataProvider.resolveErrorTraces`
  * [x] remove reliance on `Trace.previousTrace` (it seems to be inaccurate?)
    * use `previousTrace = getPreviousInContext()` instead?
  * [x] remove `getReturnTraceOfRealContext` check (it's more complicated than that)
  * [x] set error on `previousTrace` if...:
    * `trace` is `Pop` and `!isTraceReturn(previousTrace)` and `!isTraceFunctionExit(previousTrace)`
      * false-positive on try-finally, e.g. `error-try-return-finally.js` and `error3.js`

    * `trace` is `TraceType.Catch`
    * `trace` is `TraceType.Finally` and `previousTrace` is in `try` block and not `TraceType.TryExit` and `!isTraceReturn(previousTrace)` and `!isTraceFunctionExit(previousTrace)`

**Comment by MiccWan** [comment]
New algorithm works for most cases, except `nested try-finally`. See `__samplesInput__/nested-finally.js`
![image](https://user-images.githubusercontent.com/16610454/142999921-6cd84660-7271-4c71-99ce-f8831a618062.png)
