### ISSUE TITLE
Button re-shuffle

### ISSUE THREAD

**Issue by Domiii** [Domiii/dbux#202]
* [x] Remove "trace" and "error" buttons from top right toolbar
   * If we can have conditional buttons (if we can hide them dynamically) in the toolbar, keep them, and only show them when relevant
* [x] Add "Run with Dbux" button to top right toolbar
* [x] Add "Error" button to traceDetails
* [x] Add "Toggle Call Graph" button (two buttons that switch with the call graph visible status) to traceDetails (merged from #194)
* [x] Add a "Help" button to "Applications". When clicked, open our Github repository (where they will see the README with more and more information available).
   * see: https://stackoverflow.com/questions/34205481/how-to-open-browser-from-visual-studio-code-api

**Comment by MiccWan** [comment]
NOTE: `Config` button has been temporarily ignored since VScode Does node provide API to open configuraion panel(nor user/workspace setting panel).

**Comment by MiccWan** [comment]
- [] "Help button": Show confirm modal before opening website
