### ISSUE TITLE
Async Call Graph

### ISSUE THREAD

**Issue by Domiii** [Domiii/dbux#210]
Currently, we only support a "synchronous call graph", meaning that **all** execution is organized in a single serial thread. While that makes sense (especially since JavaScript is inherently single-threaded), logically we want to group "threads of asynchronous contexts" together.

That means that, for now, invocation of promise callbacks (callbacks passed to `then()`, `catch()`, `finally()` etc.), and even resuming of an `async` function will result in a new `run`, seen executing serially in the Call Graph, and you cannot easily trace a single promise or the execution of a asingle `async` function. Instead, they will be cut up into multiple pieces scattered across the linear Call Graph representation, and sprinkled with other unrelated calls that happen to occur in between.

What we want here instead is an "asynchronous call graph" representation, organized around  (and visually presenting) "asynchronous threads" running in parallel.

This feature is absolutely necessary for proper understanding modern, asynchronous JavaScript, and yet we don't have it yet. Maybe we can make this happen soon enough :)

**Comment by MiccWan** [comment]
@Domiii Maybe we can add this as a milestone?

**Comment by Domiii** [comment]
@MiccWan makes sense. [Here](https://github.com/Domiii/dbux/milestone/2) it is.
