### ISSUE TITLE
Fix ApplicationSet.busy flag -> replace with promise

### ISSUE THREAD

**Issue by Domiii** [Domiii/dbux#241]
`ApplicationSet`'s `busy`-management code has several issues:

1. The original code needs try/finally
2. It needs 110% assurance that every `inc` is **always** going to be followed by a `dec`

However, since we want to replace this with a `Promise`, the same applies:

* [ ] Make sure that any code that **might** fail is wrapped in `try(/catch)/finally`
* [ ] We must make 110% sure that `resolve` (or (hopefully not) `reject`) will be called, and called exactly once, not more, not less.

* [ ] As a side-note: The `GraphDocument` should not be in charge of the `ApplicationSet`'s `busy` state. Move to `ApplicationSet` instead.
   * (I think we discussed this before, and decided that this quickfix might be enough, but now looking at it, its probably a really bad idea :P)

```js
allApplications.selection.onApplicationsChanged(() => {
        allApplications.selection.incBusy();
        
        this.graphRoot.refresh();

        if (this.componentManager.isBusyInit()) {
          const unbind = this.componentManager.onBusyStateChanged((state) => {
            if (!state) {
              allApplications.selection.decBusy();
              unbind();
            }
          });
        }
        else {
          allApplications.selection.decBusy();
        }
      })
```

**Comment by MiccWan** [comment]
Also, since `addApplication` & `removeApplication` in `ApplicationSet.js` is checking busy state now, I'm not sure if they should be an async function that await the busyPromise after this change

**Comment by MiccWan** [comment]
## Problems
Previously, to prevent refreshing `GraphView` frequently, we added `busyState` to `ApplicationSet` and block the state change before the `busyState` ends. But actually there is no reason to handle this in `ApplicationSet`, subscriber(GraphDocument) should handle this by itself.
And another problem is, an another `applicationSelectionChange` before a `GraphRoot.refresh` is done will make the Graph build incorrectly.

## Current Status
To solve this might need to make a lot of changes, but currently we don't have full-stack example and rarely needs to handle this situation, thus remove the priority label and will come back to this after alpha launch.

**Comment by MiccWan** [comment]
## Update
From above, we'll remove the busyState management in ApplicationSet.
