### ISSUE TITLE
[traceDetailsView] add "highlight" button to "Executed Traces"

### ISSUE THREAD

**Issue by Domiii** [Domiii/dbux#265]
Originally, we had the light bulb in every `ContextNode` on the call graph.

Can we migrate that to a new button in "Executed Traces" in the `traceDetailsView`?

Code to call: `contextNodeManager.toggleStaticContextHighlight(applicationId, staticContextId);`

**Comment by MiccWan** [comment]
To do this, we have to access dbux-graph components from dbux-code, which is currently not available.
Should I make a `selectedStaticContext` in dbux-data just like `selectedTrace/Object`? Or is there any better approach?

**Comment by Domiii** [comment]
We just have to expose `contextNodeManager.toggleStaticContextHighlight(applicationId, staticContextId);` through `dbux-graph-host`'s public API, i.e. the `HostComponentManager` or somesuch... The easiest way is to just give that a 
method that will relay the call to `contextNodeManager`.



> Should I make a `selectedStaticContext` in dbux-data just like `selectedTrace/Object`? Or is there any better approach?

Don't think that is all that necessary. Right now, this seems to be the only place where we use it. Instead, we can probably also just move that to `HostComponentManager` or one of its friends.

Once the public API becomes too complex, we will have to re-design it a bit and make it more streamlined, but as long as its just a few calls, adding them to `HostComponentManager` will probably be an Ok timesafer (I hope 😄)

**Comment by Domiii** [comment]
Not important enough (for now)
