### ISSUE TITLE
After running a sample program 3 or 4 times, it says: ApplicationSet busy

### ISSUE THREAD

**Issue by Domiii** [Domiii/dbux#276]
The `busy` flag is not always cleared as it should.

I also manually enable and disable applications in the `applicationsView` several times. I think that is part of it as well.

Stacktrace:

> [DBUX RuntimeClient] init (new) /Users/domi/code/dbux/samples/case-studies/02largestOfFour/1for-bad1.js
> bundle.js:1042
> [DBUX applications] added /Users/domi/code/dbux/samples/case-studies/02largestOfFour/1for-bad1.js
> dbux-common/src/log/logger.js:120
> [DBUX RuntimeClient] init
> dbux-common/src/log/logger.js:120
> [DBUX RuntimeClient] data received; trying to addData...
> dbux-common/src/log/logger.js:120
> [DBUX RuntimeClient] init (new) /Users/domi/code/dbux/samples/case-studies/02largestOfFour/1for-bad1.js
> bundle.js:1042
> [DBUX applications] restarted /Users/domi/code/dbux/samples/case-studies/02largestOfFour/1for-bad1.js
> dbux-common/src/log/logger.js:120
> [DBUX RuntimeClient] init
> dbux-common/src/log/logger.js:120
> [DBUX RuntimeClient] data received; trying to addData...
> dbux-common/src/log/logger.js:120
> [DBUX RuntimeClient] socket event init failed Error: ApplicationSet busy
> 	at ApplicationSelection.createBusyError (/Users/domi/code/dbux/dbux-code/dist/bundle.js:3209:17)
> 	at ApplicationSelection.replaceApplication (/Users/domi/code/dbux/dbux-code/dist/bundle.js:3124:18)
> 	at AllApplications.addApplication (/Users/domi/code/dbux/dbux-code/dist/bundle.js:3570:33)
> 	at RuntimeClient._getOrCreateApplication (/Users/domi/code/dbux/dbux-code/dist/bundle.js:90684:105)
> 	at /Users/domi/code/dbux/dbux-code/dist/bundle.js:90667:33
> 	at Socket.<anonymous> (/Users/domi/code/dbux/dbux-code/dist/bundle.js:90734:9)
> 	at Socket.emit (events.js:203:13)
> 	at /Users/domi/code/dbux/dbux-code/dist/bundle.js:81652:12
> 	at processTicksAndRejections (internal/process/task_queues.js:75:11)

**Comment by MiccWan** [comment]
Maybe we should just remove the busy state management, and solve it in #241

**Comment by Domiii** [comment]
@MiccWan  Ideally yes. If it doesn't take too much time, then we would probably be better off.

However the basic problem is that the `busy` flag did not get unset in some scenario. If we moved to promises, it would be the equivalent of the `resolve` function never being called.

Can you see why the `busy` flag is never unset in that case?

**Comment by MiccWan** [comment]
ApplicationSet's busyState has been removed in PR#289, maybe we should close this?
