### ISSUE TITLE
"Highlight object traces in callgraph" is broken

### ISSUE THREAD

**Issue by Domiii** [Domiii/dbux#278]
When pressing the "Select this Object" button in the `Object Traces` node, it errors out at `ContextNodeManager.highlightByObject`: `GraphRoot`'s `GraphNode` controller component got removed somehow?

![image](https://user-images.githubusercontent.com/282899/91407980-ab3de780-e875-11ea-9f68-9e8d65097507.png)

**Comment by MiccWan** [comment]
I can't reproduce this, any example for this?
