### ISSUE TITLE
Sometimes call graph cannot be re-opened

### ISSUE THREAD

**Issue by Domiii** [Domiii/dbux#283]
I don't know yet how to reproduce it. Only happened to me once ever.

Workaround: `> Developer: Reload Window`

I saw this, and had to restart to fix it:

> stack trace: Error: [RunNode] Trying to dispose before initialized
> 	at RunNode.dispose (/Users/domi/code/dbux/dbux-code/dist/bundle.js:8751:37)
> 	at GraphRoot.dispose (/Users/domi/code/dbux/dbux-code/dist/bundle.js:8751:155)
> 	at GraphDocument.dispose (/Users/domi/code/dbux/dbux-code/dist/bundle.js:8751:155)
> 	at AppComponent.dispose (/Users/domi/code/dbux/dbux-code/dist/bundle.js:8751:155)
> 	at HostComponentManager.silentShutdown (/Users/domi/code/dbux/dbux-code/dist/bundle.js:8894:82)
> 	at reset (/Users/domi/code/dbux/dbux-code/dist/bundle.js:10680:22)
> 	at startGraphHost (/Users/domi/code/dbux/dbux-code/dist/bundle.js:10719:3)
> 	at GraphWebView.startHost (/Users/domi/code/dbux/dbux-code/dist/bundle.js:89819:231)
> 	at GraphWebView._restartHost (/Users/domi/code/dbux/dbux-code/dist/bundle.js:88444:102)
> 	at GraphWebView.restart (/Users/domi/code/dbux/dbux-code/dist/bundle.js:88339:18)
> 	at GraphWebView.show (/Users/domi/code/dbux/dbux-code/dist/bundle.js:88423:59)
> 	at showGraphView (/Users/domi/code/dbux/dbux-code/dist/bundle.js:89935:23)
> 	at /Users/domi/code/dbux/dbux-code/dist/bundle.js:89582:76
> 	at /Users/domi/code/dbux/dbux-code/dist/bundle.js:89160:22
> 	at _executeContributedCommand (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:642:374)
> 	at _.$executeContributedCommand (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:642:749)
> 	at m._doInvokeHandler (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:819:926)
> 	at m._invokeHandler (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:819:618)
> 	at m._receiveRequest (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:818:252)
> 	at m._receiveOneMessage (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:817:6)
> 	at /Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:815:161
> 	at l.fire (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:46:222)
> 	at v.fire (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:239:494)
> 	at /Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:1007:179
> 	at l.fire (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:46:222)
> 	at v.fire (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:239:494)
> 	at Object._receiveMessage (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:244:17)
> 	at /Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:241:67
> 	at l.fire (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:46:222)
> 	at p.acceptChunk (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:236:949)
> 	at /Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:236:301
> 	at Socket.t (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:245:572)
> 	at Socket.emit (events.js:203:13)
> 	at addChunk (_stream_readable.js:295:12)
> 	at readableAddChunk (_stream_readable.js:276:11)
> 	at Socket.push (_stream_readable.js:210:10)
> 	at Pipe.onStreamRead (internal/stream_base_commons.js:166:17)
>

**Comment by MiccWan** [comment]
To reproduce:
run a file and close the GraphView when adding new nodes

**Comment by Domiii** [comment]
We can discuss on Monday, if you still have doubts then :)

**Comment by MiccWan** [comment]
## To solve
maybe handle `dispose` event, and do real `silenceShutDown`(dispose no matter components are initialized) if view disposed
