### ISSUE TITLE
Do not actually activate Dbux or try to install it, unless user starts using it

### ISSUE THREAD

**Issue by Domiii** [Domiii/dbux#298]
If dependencies are not installed:

* [x] Initially, hide all Dbux tree views except one (new `preActivateView`)
* [x] In the view, show a single node that says "Start Dbux"
* [x] When clicking "Start Dbux", execute the actual "activation"
   * [x] this includes (after dependencies are installed) showing things normally and removing the view

**Comment by MiccWan** [comment]
- [ ] Add configuration `dbux.autoStart` with boolean valued
  - [ ] `false` by default
  - [ ] on `preActivate`, if `dbux.autoStart` is true, `activate` right away
