### ISSUE TITLE
Make sure that bug patch + auto commit work correctly

### ISSUE THREAD

**Issue by Domiii** [Domiii/dbux#315]
* [x] Do not checkout bug nor install, if bug was already checked out
  * Check against Project.getTagName()?

* [x] blocked by PracticeSession #118

* [x] Make sure that this also fixes the "uncommitted changes bug":
   1. run bug#4
   1. change code
   1. run bug#4 again
   1. change code again
   1. run bug#4 again
   1. -> "uncommitted changes" error

* [x] Working with multiple bugs
  1. 跑一個 bug
  1. change code
  1. 跑下一個 bug
  1. change code
  1. 再跑第一個 bug，確認修改的部分有還原
  1. 再跑第二個 bug，確認修改的部分有還原

**Comment by MiccWan** [comment]
@Domiii Tested on dev and it works fine
