### ISSUE TITLE
Review PRs

### ISSUE THREAD

**Issue by Domiii** [Domiii/dbux#334]
@陳冠宇
 這行是多餘的嗎?
https://github.com/Domiii/dbux/pull/329/files#diff-8ab13e53cc802676659dde2ba8e6f742R97

@陳冠宇
 為甚麼在這裡 dispose? 感覺這樣沒辦法觀察過程跟結果? (有時候很需要)
https://github.com/Domiii/dbux/pull/326/files#diff-599cd1f1e9d6d3fa5bab7ad0daf76f2cR136

@陳冠宇
 你這裡 merge 的時候不小心覆蓋掉我已經改變的東西~ 請幫忙還遠~ 以後 merge 的時候有辦法可以小心一點嗎? 還是你覺得這個是怎麼發生的? 我怕說以後會有一個因為東西被覆蓋掉，因此已經修好的 bug 會復活的大機會，有點可怕 :/
https://github.com/Domiii/dbux/pull/326/files#diff-599cd1f1e9d6d3fa5bab7ad0daf76f2cR111

**Comment by edisonhello** [comment]
1. 不太懂，我們不是要得到 node 的版本嗎？或是用 volta 之後就無所謂了？
2. 那個 dispose 的來源好像是 commit: 649641fd5 的東西？我應該要把他拔掉嗎？
3. 我加了一個 commit 修這個東西，不確定這是不是妳想要的樣子。感覺應該是 merge 的時候 git 的判斷？或是其實有 conflict 只是我在手動 merge 的時候我沒注意到？我也不太確定 QQ
