### ISSUE TITLE
PathwaysView will not listen on pdp if PracticeSession is recovered from memento

### ISSUE THREAD

**Issue by MiccWan** [Domiii/dbux#368]
### Problem

`pdp.onData('userActions', this.view.refresh)`@PathwaysDocument.js:32 will not be called if PracticeSession is recovered from memento, since the `onPracticeSessionChanged` event is called before the view is initialized.

**Comment by Domiii** [comment]
@MiccWan  any updates?
I think this is fixed, since we are not loading from memento anymore, right?

**Comment by MiccWan** [comment]
It works good now
