### ISSUE TITLE
Enable loading of log files from other machines

### ISSUE THREAD

**Issue by Domiii** [Domiii/dbux#377]
Goal: We want to be able to load and analyze log files from anyone anywhere. However, when loading log files from other machines, absolute file paths won't match.

# Add command to load existing log files

* [x] (as usual) check if we need to give up current session
* [x] when loaded:
  * automatically start session
  * automatically select corresponding bug (in the current setup this should already work as-is; it will install everything necessary for the bug, but will not run the test)
  * open the `PathwaysWebview`

* [x] Make sure it works with files from own system
* [x] Make sure it works with files from other's system
  * recover `Project` from log file information (not sure; do we store projectName in log files?)
  * when resolving filepaths, maybe do some `regex` magic to resolve them relative to local `projectPath`?
  * throw an error if regex magic didn't work (files cannot be found)

# Fix file paths when saving log files: store relative, rather than absolute paths

* [x] need to change to some sort of `relativeFilePath` in `StaticProgramContext.fileName`
* [x] need to first figure out `projectPath` relative to `Application.applicationEntryPointPath`?
  * NOTE: we want to resolve the `applicationEntryPointPath` relative to the dbux-practice `projectPath` in order to determine the actual `relativePath`
  * NOTE: we tried something like that in `CodeApplication.getRelativeFolder`, but it won't work if the project is not loaded into the workspace
  * (skipped)so we need to find a way to connect `ProjectsManger.projectPath` to `Application.applicationEntryPointPath` when the application is added (must happen at that exact moment in time, so that once data comes in, it can get a correct `relativePath`)
  * resolve the `relativePath` via a "post add hook" in `RuntimeDataProvider.js` in `StaticProgramContextCollection` (see how post hooks are added in other collections, e.g. `ExecutionTraceCollection`)
* [x] when loading the log file on a different system, resolve that `relativePath` relative to the corresponding folder on the local system instead
* [ ] also fix slashes in path (simply prefer `/` over `\\`)

**Comment by MiccWan** [comment]
Currently we reduced the problem to the following: 
* [ ] resolve `StaticProgramContext.relativePath` when addData
* [ ] derive `StaticProgramContext.filePath` from `StaticProgramContext.relativePath` on load

**Comment by MiccWan** [comment]
Update: Needs cross platform tests.

**Comment by MiccWan** [comment]
Update: able to load log files from experiment(10/24)

**Comment by MiccWan** [comment]
Update: Checked to work on my PC
