### ISSUE TITLE
`doExport` errors

### ISSUE THREAD

**Issue by edisonhello** [Domiii/dbux#393]
### Problem

When exporting application data:
```
[DBUX Command] 'dbux.exportApplicationData' failed: Error: ENOENT: no such file or directory, open '/home/edison/Coding/dbux/analysis/__data__/-home/edison/Coding/dbux/dbux_projects/express/test_data.json'
	at Object.openSync (fs.js:440:3)
	at Object.func [as openSync] (electron/js2c/asar.js:140:31)
	at Object.writeFileSync (fs.js:1265:35)
	at doExport (/home/edison/Coding/dbux/dbux-code/dist/bundle.js:83551:47)
	at /home/edison/Coding/dbux/dbux-code/dist/bundle.js:83569:11
	at processTicksAndRejections (internal/process/task_queues.js:94:5)
	at async /home/edison/Coding/dbux/dbux-code/dist/bundle.js:83108:16
```

### Cause

function `doExport` uses `Application.getSafeFileName` as log file name, but it returns the full path instead of only file name.

**Comment by Domiii** [comment]
@MiccWan already found it out: There was no relative path (because only a single file got executed), so the absolute path got added.

**Comment by Domiii** [comment]
We don't need this feature for now, as Pathways actually tracks all application information anyway. Closing.
