### ISSUE TITLE
When closing or cancelling Terminal command, dbux-practice stays "currently busy" forever

### ISSUE THREAD

**Issue by Domiii** [Domiii/dbux#401]
We had this bug:

* [x] When closing or cancelling Terminal command, dbux-practice stays "currently busy" forever

Steps to reproduce:

* Run a dbux-practice bug
* Cancel in terminal (e.g. CTRL+C)
* -> Try doing anything -> Always "currently busy"

That happened because the code has a big problem:

* There were multiple `window.onDidCloseTerminal` handlers that acted in conflict with one another.

Also, the entire code looks like someone started working on it, then someone else worked on it, and there was no communication on how things should work (😄 ）. There are several more issues:

* `dispose` does not get called consistently
* `watcher` is somehow only a local variable, not a field. Thus `dispose` does not take care of it.
* There are probably more problems leading to more inconsistencies and bugs.......

When testing, especially the first bug (always "currently busy") should have been very obvious. Maybe we can review how to test things :)

**Comment by edisonhello** [comment]
Can not reproduce @Domiii
