### ISSUE TITLE
Cofify Pathways Timeline

### ISSUE THREAD

**Issue by Domiii** [Domiii/dbux#408]
Pathways timeline:

* [x] render a timeline, partitioned by step
* [x] add "stale" binary layer
  * [x] if no new staticTrace has been visited for more than X seconds (e.g. X = 60), consider the process stale, as the developer is only investigating previously investigated code.
  * [x] for callGraph actions involving call graph nodes that also have a trace, use that trace in the same way (currently we only have `parentTrace`, but we can uniquely identify it's child staticTrace)
* [x] check if all that already works for previous logs

* [x] make sure that ActionGroups can wrap inside of a `StepGroup`. If not, remove `Step` in `Analyze` mode, and add some border (or "divider") element between ActionGroups of different steps
  * [x] Also, add step's backgroundColor to ActionGroup, so step color still looks correct even though Steps are not actually rendered

**Comment by MiccWan** [comment]
NOTE: Currently every CallGraph event has record trace already, except `UserActionType.CallGraphNodeCollapseChange`, but I didn't record its data correctly so we can't use them in the logs from first experiment 😢 . This is fixed in the next PR
