### ISSUE TITLE
Fix pathways: Steps not merged correctly + color maybe wrong sometimes?

### ISSUE THREAD

**Issue by Domiii** [Domiii/dbux#438]
* [x] Happens when one first clicks into a function (sending an `EditorSelectionChanged` event).
  ![image](https://user-images.githubusercontent.com/282899/103130061-17badd00-46d6-11eb-99e1-e361eb364484.png)
* [x] Express#18, these contexts all seem to have the exact same color?
  ![express18_path](https://user-images.githubusercontent.com/282899/103130298-150cb780-46d7-11eb-92c1-0838e36b703c.png)
  * Probably related to the fact that `callId`s are not resolved correctly. We track that issue separately in #389

**Comment by MiccWan** [comment]
Confirmed that the color are not exactly the same, these three StaticContexts are just happened to have similar color

**Comment by MiccWan** [comment]
I think we have found this problem in #424 , we may also close it after this PR is merged
