### ISSUE TITLE
[Call Graph] in `ContextNode`: split `nodeToggleBtn` into two

### ISSUE THREAD

**Issue by Domiii** [Domiii/dbux#455]
Goal: don't accidentally expand the entire sub-tree (since that can be bad for performance) if you only want to toggle between showing and not showing children. For that, we want to offer another button, so we are not forced to toggle through all modes.

* [x] in `ContextNode`: remove the original `nodeToggleBtn`
* [x] add two new buttons side-by-side: `nextMode` and `previousMode`
  * [x]  make them less wide, so they use (roughly) the same width as the single original button
* [ ] if there is only 2 modes (no nested descendants, and thus no third mode), disable the unused button

* This issue is related to call graph optimization. Next issue in line: #471

**Comment by MiccWan** [comment]
What icons should I put on the new buttons?
