### ISSUE TITLE
Call Graph: Load/render roots (and each root's subtree) separately

### ISSUE THREAD

**Issue by Domiii** [Domiii/dbux#458]
* [x] When first loading the call graph, only transfer and render the roots
* [x] Only when clicking an individual root, load and render it's subtree
* [x] We probably need a new type of node `RootNode`; probably `RootNode extends ContextNode`
* [x] Make sure, functions that automatically expand nodes (e.g. `sync mode` and `search`) still work
* [ ] Merge multiple successive roots of same `staticContextId` into one node (similar to repeated `console.log`s with same output)
  * Discuss with Domi first: we will need more "grouping" nodes moving forward. We might want to revisit and fix up the existing node management systems, and then add a more robust "grouping" feature first.

* This issue is related to call graph optimization. Next issue in line: #455

**Comment by MiccWan** [comment]
@Domiii The last task is also raised in #464, maybe we can close this one?

**Comment by Domiii** [comment]
> @Domiii The last task is also raised in #464, maybe we can close this one?

Makes sense!
