### ISSUE TITLE
Add config to whitelist node_modules

### ISSUE THREAD

**Issue by edisonhello** [Domiii/dbux#462]
* [x] Add setting to vscode.
* [x] Add yargs setting in `commandCommons.js`.
* [x] Pass the setting when calling dbux-cli.
* [x] Write a function that receive path and array of whitelisted modules (maybe a regex?), returns a bool indicates whether this file should be ignored.
* [x] Apply to dbux-cli first and test.

**Comment by Domiii** [comment]
@edisonhello hi! Is this working with `dbux-cli`?

Probably needs a bit more work for webpack, because there, we also need to add corresponding paths to the `babel-loader` with `dbux` enabled.

**Comment by Domiii** [comment]
Whitelist tested and works!

**Comment by Domiii** [comment]
Future work:

* [ ] Move `dbux-cli\src\buildBabelOptions.js` to a new place and package it so that bundlers (webpack etc.) can easily use it. Possibly create `dbux-webpack-plugin` for that purpose.
