### ISSUE TITLE
Optimize Call Graph to deal with 50+k nodes per root

### ISSUE THREAD

**Issue by Domiii** [Domiii/dbux#471]
* [ ] Things get too slow when a call graph root has many descendants. Test this with Chart.js#2. There are 40+k descendants in some of the roots.
  * Make sure to use the right settings so that things don't slow down to a grinding halt:
    * Run without debugging ![image](https://user-images.githubusercontent.com/282899/111025465-4a47bc80-841f-11eb-84ed-526f76aeba7e.png)
    * in `dbux-runtime\src\RuntimeMonitor.js` set `tracesDisabled` from `0` to `1`
  * [x] When working with such a root or its children, things get extremely slow. Find a way to fix this.
* [x] Do some preliminary performance profiling
  * Turns out, it can render the graph roots real quick (about 1 second).
  * After the first second, it will asynchronously keep adding everything else for some 10-20 seconds (16s in my case). While doing that, the Graph view is interactive, but too laggy to use.
  * Summary: Total time spent running our code = 11.1s
    ![image](https://user-images.githubusercontent.com/282899/110964668-63545d00-838e-11eb-92e5-963453235b8f.png)
  * Flamegraph (while building graph initially; after a Graph view restart):
    ![image](https://user-images.githubusercontent.com/282899/110962576-15d6f080-838c-11eb-80e4-42ddf9a1e733.png)
  * Tasks: This indicates, that the rasterizer thread is probably a bottleneck. (because we are adding that many nodes to HTML)
    ![image](https://user-images.githubusercontent.com/282899/110963402-fd1b0a80-838c-11eb-8c65-e1ba28cc7eb0.png)
  * Scripting breakdown (Total Time)
    ![image](https://user-images.githubusercontent.com/282899/110963847-8599ab00-838d-11eb-9b91-23eaff509c9b.png)
  * Scripting breakdown (Self Time)
    ![image](https://user-images.githubusercontent.com/282899/110964034-b5e14980-838d-11eb-949c-89b3a06f9f01.png)
  * Confirmed: HTML rendering takes a lot of time (half of the total time spent (11.1s))
    ![image](https://user-images.githubusercontent.com/282899/110965866-9d722e80-838f-11eb-96e2-8fc9b84e93b6.png)

* Maybe clear up some inconsistencies in above analysis result:
  * [ ] Why does `compileHtmlElement` have three very different numbers?
    * `Self Time = 2.7s`, `Total Time = 4.2s` and the time spent inside it's `template.html = html` line is `5.8s`
    * Maybe I made a mistake recording it? Maybe we should start by repeating the analysis one more time to confirm.

## Improve performance

* [x] Lazy load for all nodes.

* Other possible ideas:
  * New "omission node" feature:
    * If a context of same `staticContextId` has already been rendered within the same root (let's call them "repeated contexts"), add an omission node instead.
    * For any other "repeated context" that is either (i) a child of, or (ii) is following (on the timeline) an "omission node" : merge into the omission node.
  * We might have to lazy-load all layers, not just the root layer... ?
  * Maybe reducing `components`/`controllers` can help a little bit (but probably not much)

**Comment by Domiii** [comment]
I found re-opening a node is very slow, even though, no `html` is created etc. I found the issue to be the recursive `setMode` function calling `update` on all children.

The fix was:

```js
    if (this.state.mode === mode) {
      // nothing left to do
      return;
    }
```

**Comment by MiccWan** [comment]
Update: Try to apply `ContextNode lazy load` in issue #458 and PR #477 to all `ContextNode` instead of adding new `isEnabled` logic
