### ISSUE TITLE
Call graph: "Expand Subtree" button broken

### ISSUE THREAD

**Issue by Domiii** [Domiii/dbux#483]
Steps to reproduce:

* In todomvc-es6#2 (or any other bug), click on "Expand Subtree" of `onLoad`. It will only open up two levels:
  ![image](https://user-images.githubusercontent.com/282899/112747831-713eea80-8fea-11eb-9660-2333c5067e83.png)
  * NOTE: it works fine when clicking it a second time.
  * NOTE: does not depend on whether the node has an error or not.

**Comment by MiccWan** [comment]
@Domiii I think this is also fixed in PR #482

**Comment by Domiii** [comment]
Ah yes, it is probably this: https://github.com/Domiii/dbux/pull/482/files#diff-0b6df76a85acb3b0bae2cffe21dcf6e42a5fdd4512dd1f34f56177176896e155L142
