### ISSUE TITLE
PDP should handle new RDP data

### ISSUE THREAD

**Issue by MiccWan** [Domiii/dbux#494]
Currently PDP is not recording new RDP data after the application is saved. Projects like `Todo-MVC` that generates data after user actions will not be recorded correctly.

- [x] Make PDP listen on RDP's data
  - [x] Serialize `newData` in some way and incrementally add to log file

**Comment by Domiii** [comment]
Let's stop this for now.  First need to find a way to support (and also store remotely) PDP data when dealing with applications with very large trace data.
