### ISSUE TITLE
Error reporting after run dbux-code(dbux)

### ISSUE THREAD

**Issue by Nehcled** [Domiii/dbux#531]
Error reporter after run dbux-code(dbux).
It was working normal last week.
![image](https://user-images.githubusercontent.com/48467776/121770514-4b15f900-cb9c-11eb-9461-0e9069e8eddf.png)

message:
> [Dbux dbux-code] Starting Dbux v0.4.4-dev.0 (mode=development, (dev only) DBUX_ROOT=C:/Users/Yggdrasill/dbux)...
> c:\Users\Yggdrasill\AppData\Local\Programs\Microsoft VS Code\resources\app\out\bootstrap-fork.js:5
> [Dbux projectControl] Initializing dbux-projects: projectsRoot = "c:\Users\Yggdrasill\dbux\dbux_projects", dependencyRoot = "c:\Users\Yggdrasill\dbux"
> dbux-common/src/log/logger.js:178
> [Dbux PracticeManager] getDbuxPath(), relativePath='@dbux/cli/bin/dbux.js', getDbuxRoot()='C:/Users/Yggdrasill/dbux', config={"dependencyRoot":"c:/Users/Yggdrasill/dbux","projectsRoot":"c:/Users/Yggdrasill/dbux/dbux_projects","dbuxLanguage":"en"}
> dbux-common/src/log/logger.js:178
> [Dbux installUtil] Checking library dependencies. Found 0 missing: 
> dbux-common/src/log/logger.js:178
> [Dbux PathwaysDataProvider] Cannot recover application: log file not found at c:\Users\Yggdrasill\dbux\dbux-code\logs\edbdbc94-3499-4cdc-a17e-ce2aa6cbeaab.dbuxapp
> c:\Users\Yggdrasill\AppData\Local\Programs\Microsoft VS Code\resources\app\out\bootstrap-fork.js:5
> [Dbux PathwaysDataProvider] No log file found at "c:\Users\Yggdrasill\dbux\dbux-code\logs\a91e80ba-0016-4b80-8450-dfe2e86b44d5.dbuxlog", header written
> c:\Users\Yggdrasill\AppData\Local\Programs\Microsoft VS Code\resources\app\out\bootstrap-fork.js:5
> [Dbux PracticeManager] Unable to load PracticeSession: Error: EEXIST: file already exists, open 'c:\Users\Yggdrasill\dbux\dbux-code\logs\a91e80ba-0016-4b80-8450-dfe2e86b44d5.dbuxlog'
> 	at Object.openSync (fs.js:476:3)
> 	at Object.func [as openSync] (electron/js2c/asar_bundle.js:5:1846)
> 	at Object.writeFileSync (fs.js:1467:35)
> 	at Object.appendFileSync (fs.js:1506:6)
> 	at PathwaysDataProvider.writeHeader (c:\Users\Yggdrasill\dbux\dbux-code\dist\bundle.js:31655:47)
> 	at PathwaysDataProvider.load (c:\Users\Yggdrasill\dbux\dbux-code\dist\bundle.js:31648:651)
> 	at PathwaysDataProvider.init (c:\Users\Yggdrasill\dbux\dbux-code\dist\bundle.js:31644:32)
> 	at ProjectsManager._resetPracticeSession (c:\Users\Yggdrasill\dbux\dbux-code\dist\bundle.js:27656:14)
> 	at ProjectsManager.recoverPracticeSession (c:\Users\Yggdrasill\dbux\dbux-code\dist\bundle.js:27660:471)
> 	at ProjectsManager.init (c:\Users\Yggdrasill\dbux\dbux-code\dist\bundle.js:27634:181)
> 	at c:\Users\Yggdrasill\dbux\dbux-code\dist\bundle.js:9269:26

**Comment by Domiii** [comment]
`PathwaysDataProvider.writeHeader` - `Unable to load PracticeSession: Error: EEXIST: file already exists`

**Comment by MiccWan** [comment]
Looks like there are potential race condition? I might not be able to reproduce this error.
Does it still happen after using `Dbux Dev: Reset Practice Progress` command?

**Comment by Domiii** [comment]
More detailed report in #540
