### ISSUE TITLE
Fix async error stack (part 13)

### ISSUE THREAD

**Issue by Domiii** [Domiii/dbux#662]
* [x] fix: When error is thrown from `async` function, previous `await` nodes are tagged as errors
* [x] test w/ `sequelize` -> `findOrCreate-parallel`
  * The circles mark nodes where error was thrown. The other nodes (BEFORE the actual error) should not be "on fire":
  * ![image](https://user-images.githubusercontent.com/282899/151777451-63fe16d4-5c63-4193-b640-c52ce682e665.png)

**Comment by MiccWan** [comment]
### Solution
Only apply fire icon on root cause, but not the ascendants.
