### ISSUE TITLE
Wrong version of node ??

### ISSUE THREAD

**Issue by donPab** [Domiii/dbux#772]
==about VSCode
Version: 1.75.1 (system setup)
Date: 2023-02-08T21:32:34.589Z
Electron: 19.1.9
Chromium: 102.0.5005.194
Node.js: 16.14.2		I don’t know where VSCode gets this.  node -v shows 18.14.0
V8: 10.2.154.23-electron.0
OS: Windows_NT x64 10.0.19044
Sandboxed: No

==launch.json    from app under test
    {
      "name": "LaunchDebugMainProcess",
      "type": "node",
      "request": "launch",

      "runtimeExecutable": "${workspaceRoot}/node_modules/.bin/electron",
      "runtimeArgs":["--no-sandbox"  ],

      "cwd": "${workspaceRoot}",
      "program": "${workspaceRoot}/index.js",
      "args": [],
      "stopOnEntry": false,
      "sourceMaps": false,
      "outputCapture": "std",

      "preLaunchTask": ""
    },

==note:  index.js is part of Evolus.Pencil drawing app

==False Error    node version should be ok;  it is not OLD 
 [Dbux] Dbux requires the following programs to be installed and available on your system in
order to run smoothly. Please make sure, you have all of them installed.
\/ shell
found at "C:/WINDOWS/SYSTEM32/CMDEXE"
\/ node
Installed but old. Version is 18.14.0 but we recommend 16.
\/ npm
found at "C:/PROGRAM FILES/NODEJS/NPM.CMD"
FAILED: One or more system dependencies are not installed. Fix them, then try again.

**Comment by Domiii** [comment]
I am not sure what this has to do with Dbux?
